# -*- coding: utf-8 -*-
"""Hw2_CV_MKh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTwfOTpQfXsWaeJ6xroMnJzsk9uSvu5v

# تمرین دوم -
## OpenCv
"""

## Importing necessary libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
#from cv2 import cv2_imshow

"""## 1-1) Load Image"""

# Load the image
image = cv2.imread('Goerge Micheal.jpg')

# Convert the image to RGBA (with an alpha channel)
image_rgba = cv2.cvtColor(image, cv2.COLOR_BGR2BGRA)

plt.figure(figsize=[10,5])
plt.subplot(1,2,1); plt.imshow(image_rgba[:,:,::-1]); plt.title("RGBA Picture")
plt.subplot(1,2,2); plt.imshow(image[:,:,::-1]); plt.title("RGB Picture")

"""## 1-2) Detecting Face and Adding Alpha"""

from google.colab.patches import cv2_imshow
# Define the face region manually (x, y, width, height)
x, y, w, h = 550, 0, 600, 500  # Example coordinates

# Set alpha to 255 (Foreground) for the face region
image_rgba[y:y+h, x:x+w, 3] = 255 #alpha = 255/255 = 1

# Set alpha to 100 (Background) for the rest of the image
image_rgba[:, :, 3] = np.where(image_rgba[:, :, 3] == 255, 255, 50) #50/250 = 20% Foreground
#alpha == 0.2 --> 0

# Display the result (optional)
cv2_imshow(image_rgba)
cv2.waitKey(0)
cv2.destroyAllWindows()

"""## 1-3)Loading and Saving the output"""

image_rgba.shape

# Save the output image as a PNG file or gif file
cv2.imwrite('Transparent_image.png', image_rgba)

"""## Another Way"""

cropped = image[0:500, 500:1100]
print(cropped.shape)
png_img = np.zeros((500,600,4), 'uint8')
png_img[...,0:3] = cropped #Allocating the first 3 channel as RGB

circle = np.zeros((500, 600), np.uint8)
cv2.circle(circle, (250,800), 275, (255,255,255), -1) #creating a circle with appropriate radius and center

png_img[...,3] = circle #allocating the 4th channel, alpha

plt.figure(figsize=[10,5])
plt.subplot(1,2,1);plt.imshow(cropped[:,:,::-1]); plt.title("Cropped face")
plt.subplot(1,2,2); plt.imshow(png_img[:,:,::-1]); plt.title("Cropped Image AND Circle")

# Save the output image as a PNG file or gif file
cv2.imwrite('Trans_Goerge_2ndway.png', png_img)

"""# Seyedali Seyedhosseini
## The End
"""