# -*- coding: utf-8 -*-
"""Hw3_CV_MKh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTwfOTpQfXsWaeJ6xroMnJzsk9uSvu5v

# تمرین سوم -
## OpenCv

## Loading Relevant Libraries and Packages
"""

## Importing necessary libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
#from cv2 import cv2_imshow

?cv2.rectangle

?cv2.line

img = np.zeros((1024, 1024, 3), np.uint8)

cv2.rectangle(img, (200,400), (800,800), (255,0,0), 12) #House
cv2.line(img, (200,400), (500, 200), (0, 255, 128), 14) #Ceiling
cv2.line(img, (500,200), (800, 400), (0, 0, 255), 14) #Ceiling
cv2.rectangle(img, (450,280), (550,380), (255,255,255), 10) #Upfloor window
cv2.rectangle(img, (650,580), (800,800), (255,255,0), 8) #Door
cv2.rectangle(img, (300,500), (500,650), (0,255,0), 6) #Front Window


plt.imshow(img[:,:,::-1]); plt.title("Raw Image")

cv2.imwrite('Drawn House.png', img)

"""# Seyedali Seyedhosseini
## The End
"""