# -*- coding: utf-8 -*-
"""Hw1_CV_MKh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTwfOTpQfXsWaeJ6xroMnJzsk9uSvu5v

# تمرین اول - بخش اول: برش تصویر
## OpenCv
"""

## Importing necessary libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt

"""### 1-1)Loading The File"""

img = cv2.imread('Goerge Micheal.jpg')
plt.imshow(img[:, :, ::-1]) #Pyplot uses BGR color space while we want to depict them in RGB
plt.title("Goerge Michael at his height")

"""### 1-2)Cropping and Displaying the Face"""

cropped_img = img[0:500, 500:1100] #Approximately filling in the height(rows) and width(columns) of the face
plt.imshow(cropped_img[:, :, ::-1])
plt.title("Goerge Michael`s Face")

"""### 1-3)Saving into a new file"""

cv2.imwrite('Face.png', cropped_img)

"""# Seyedali Seyedhosseini
## The End
"""